name: Deploy Functions

on:
  workflow_dispatch:
    inputs:
      functions:
        description: "Comma separated function names"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ''
      SUPABASE_PROJECT_ID: ''

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          supabase link \
            --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy Selected Functions
        run: |
          IFS=',' read -ra FUNCTIONS <<< "${{ github.event.inputs.functions }}"

          for fn in "${FUNCTIONS[@]}"; do
            fn=$(echo "$fn" | xargs)
            echo "Deploying $fn"
            supabase functions deploy "$fn"
          done
